apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-job-cleaner
  namespace: kube-system
  labels:
    application: kube-job-cleaner
    version: "0.1"
spec:
  schedule: "17 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            application: kube-job-cleaner
            version: "0.1"
        spec:
          serviceAccountName: kube-job-cleaner
          restartPolicy: OnFailure
          containers:
          - name: cleaner
            image: "devopszcom/kube-job-cleaner:0.1"
            resources:
              limits:
                memory: 100Mi
              requests:
                cpu: 20m
                memory: 50Mi
